### ISSUE TITLE
Don't scan the code itself

### ISSUE THREAD

**Issue by fridrich** [openSUSE/cavil#1]
Things like "throw IllegalArgumentException();" in a code trigger Risk 9 because of the string legal being part of the exception name. Also, comments that state what is "legal" or "illegal" as an input for a function to the same. Would there be a way to make the scanning more smart and avoid a load of false positives?

**Comment by coolo** [comment]
IllegalArgumentException doesn't trigger legal - we don't parse strings, we parse words. There must be a comment near that.

And differentiating code from non-code sounds like a neat idea, but hard to do with so many different languages we parse. And then you have perl packages, who's only hint about a license is a Makefile.PL that states license=>'perl5'

So erasing false positives is a goal, but too hard to do during parsing - so I'm trying to erase them afterwards.
