### ISSUE TITLE
 2-clause BSD license recognized as BSD unspecified

### ISSUE THREAD

**Issue by lkocman** [openSUSE/cavil#103]
We can get a bit better at recognizing particular BSD license. See my example
Following snippet was recognized as BSD with unspecfied version, while it's clearly stated it's BSD-2-Clause

```
src/regex/tre*) is Copyright © 2001-2008 Ville Laurikari and licensed	
under a 2-clause BSD license (license text in the source files). 
```
Even the opensource.org calls it "2-Clause BSD License"
[POPULAR / STRONG COMMUNITY](https://opensource.org/licenses/?categories=popular-strong-community)
The 2-Clause BSD License
SPDX short identifier: BSD-2-Clause

**Comment by lkocman** [comment]
Closing my bad ... it was another part of the same copyright ...

**Comment by kraih** [comment]
You can also browse the license list at https://legaldb.suse.de/licenses to see if there are any patterns with the wrong license name. Moving them around is a very minor change.
