### ISSUE TITLE
Prevent obs_import race condition

### ISSUE THREAD

**Issue by kraih** [openSUSE/cavil#41]
Reported by @coolo. If the same package is requested multiple times in quick succession it might be possible to create the same `obs_import` job multiple times, resulting in a race condition.

**Comment by coolo** [comment]
If you're lucky, you get failed minion jobs on index or unpack. If you're unlucky you get invalid reports.

IMO we need to make sure there is only one job set per package at any given time, because this also impacts performance even for the jobs where it doesn't harm.

**Comment by kraih** [comment]
The main problem of race conditions should be fixed now. But once Minion has upstream support for batch jobs (probably weeks or months away still) i'd like to switch to those to make lock management easier and a bit safer.

**Comment by kraih** [comment]
I've not seen an import race condition in a long time, so the problem is probably gone. And there are no new upstream features planned anymore for batch jobs. So i guess we can consider this resolved.
