### ISSUE TITLE
Carwos project "API"

### ISSUE THREAD

**Issue by llansky3** [openSUSE/cavil#51]
As discussed over an email.

Background: Our CI legal pipeline that produces license report for
our customer depends on retrieving JSON from legaldb.suse.de and it has
been changing recently.

We rely on following interfaces (accessed with header containing "carwos" token in place and "Accept: application/json"):

url = f"http://legaldb.suse.de/package/{report_id}"
url = f"http://legaldb.suse.de/reviews/calc_report/{report_id}"
url = f"http://legaldb.suse.de/reviews/fetch_source/{file_id}"
url = "http://legaldb.suse.de/packages?" + urlencode(info)
(the report_id e.g. 232522, file_id is e.g. 7115234143 etc.)

We can fix the query at our end (e.g. to url = f"http://legaldb.suse.de/reviews/calc_report/{report_id}.json) but we would like to ensure that such defined interface is not changing too often or disappears completely.

**Comment by kraih** [comment]
Seems reasonable, i'll make public APIs for those.

**Comment by llansky3** [comment]
So just to be clear  - our current "recently updated" interface uses following:
url = f"http://legaldb.suse.de/package/{report_id}"
url = f"http://legaldb.suse.de/reviews/calc_report/{report_id}**.json**"
url = f"http://legaldb.suse.de/reviews/fetch_source/{file_id}**.json**"
url = "http://legaldb.suse.de/packages?" + urlencode(info)

**Comment by kraih** [comment]
Those will become `/api/...` when they are part of the official API.

**Comment by llansky3** [comment]
Perfect....we can then adjust the queries at our end! Thanks!

**Comment by llansky3** [comment]
Hi Sebastian, one more question regarding the API: currently we are querying the information we need in sequence but there is no obstacle at our end to parallelize things to query the information in parallel. Yet @coolo has raised a valid concern about jamming the legaldb and thus screwing everyone else. Any thoughts on how "parallel" we could get with our queries from your end? Thanks.

**Comment by kraih** [comment]
Yes, please don't parallelise the process, the hardware is not set up for that. We'd run out of memory at peak times.

**Comment by llansky3** [comment]
OK, clear - we'll park this parallelization for now. But please keep us updated in case you hardware situation would improve and this would open some doors to such parallelization (or if our use case would somehow help you to justify better hardware)

**Comment by kraih** [comment]
Ok, two of those endpoints were already part of the bot API, and i've added the other two now.
```
http://legaldb.suse.de/reviews/calc_report/{report_id}.json
becomes
http://legaldb.suse.de/package/{report_id}/report

http://legaldb.suse.de/reviews/fetch_source/{file_id}.json
becomes
http://legaldb.suse.de/rsource/{file_id}
```
And both will always return JSON with 200 OK responses. Token authentication is the same for all of them.
