### ISSUE TITLE
Show the original string if SPDX parsing fails

### ISSUE THREAD

**Issue by coolo** [openSUSE/cavil#53]
For spec files not coming from openSUSE, cavil is making it hard to review the rpm license as it enforces SPDX. If SPDX parsing fails, it should show the original rpm license with the information that spdx mapping failed included.

**Comment by kraih** [comment]
Agreed, Cavil should always show as much information as it can.

**Comment by kraih** [comment]
The feature is implemented. No tests yet since this was time sensitive, but i'll add those as well now.
